
package org.example;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CurrencyConversionService", targetNamespace = "http://example.org/", wsdlLocation = "http://localhost:1234/currencyconversion?wsdl")
public class CurrencyConversionService
    extends Service
{

    private final static URL CURRENCYCONVERSIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CURRENCYCONVERSIONSERVICE_EXCEPTION;
    private final static QName CURRENCYCONVERSIONSERVICE_QNAME = new QName("http://example.org/", "CurrencyConversionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1234/currencyconversion?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CURRENCYCONVERSIONSERVICE_WSDL_LOCATION = url;
        CURRENCYCONVERSIONSERVICE_EXCEPTION = e;
    }

    public CurrencyConversionService() {
        super(__getWsdlLocation(), CURRENCYCONVERSIONSERVICE_QNAME);
    }

    public CurrencyConversionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CURRENCYCONVERSIONSERVICE_QNAME, features);
    }

    public CurrencyConversionService(URL wsdlLocation) {
        super(wsdlLocation, CURRENCYCONVERSIONSERVICE_QNAME);
    }

    public CurrencyConversionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CURRENCYCONVERSIONSERVICE_QNAME, features);
    }

    public CurrencyConversionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CurrencyConversionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CurrencyConversion
     */
    @WebEndpoint(name = "CurrencyConversionPort")
    public CurrencyConversion getCurrencyConversionPort() {
        return super.getPort(new QName("http://example.org/", "CurrencyConversionPort"), CurrencyConversion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CurrencyConversion
     */
    @WebEndpoint(name = "CurrencyConversionPort")
    public CurrencyConversion getCurrencyConversionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.org/", "CurrencyConversionPort"), CurrencyConversion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CURRENCYCONVERSIONSERVICE_EXCEPTION!= null) {
            throw CURRENCYCONVERSIONSERVICE_EXCEPTION;
        }
        return CURRENCYCONVERSIONSERVICE_WSDL_LOCATION;
    }

}
